version: '2'
services:
  mysql:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'docker'
      MYSQL_PASS: 'docker'
    volumes:
      - ./data:/var/lib/mysql
volumes:
  data: