version: '2'
services:
  postgres:
    image: postgres:latest
    container_name: pg_database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'tcc'
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d